apiVersion: v1
kind: CustomResourceDefinition
metadata:
  name: certificatesigningrequests.certificates.k8s.io
spec:
  group: certificates.k8s.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          request:
            type: object
            properties:
              apiGroup:
                type: string
              kind:
                type: string
              issuerRef:
                type: object
                properties:
                  kind:
                    type: string
                  name:
                    type: string
              commonName:
                type: string
              subjects:
                type: array
                items:
                  type: object
                  properties:
                    organizationName:
                      type: string
              usages:
                type: array
                items:
                  type: string
              extra:
                type: object
                properties:
                  keyUsage:
                    type: string
                  extendedKeyUsage:
                    type: string
  scope: Namespaced
  names:
    plural: certificatesigningrequests
    singular: certificatesigningrequest
    kind: CertificateSigningRequest
    shortNames:
    - csr
