apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: myserver
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1pEQ0NBVXdDQVFBd0h6RWRNQnNHQTFVRUF3d1ViWGx6WlhKMlpYSXVaR1ZtWVhWc2RDNXpkbU13Z2dFaQpNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURVUWliZkdKMGpqTWdsaHBTSVdnbUFJQ0VMCk54OVRkYmhhWm00TGkxcTRBZ2VDUFpUQ05QVzdZT1c1Y2lEa2QyZWFsZjRPS0pnQkUvcHhtMjRGT2toOUdtZHMKOEVORzg5NSswUlJqZ1AvYkxUR281TkZzTENHS3VCWWRUZEprZHVMckRYUHlNY0tPN0VvRldHVXdQRGZNdVZQZQpYSzFCTm95aFp0YjMzVThGRW9GZy9TUkRub2lURGZ6ODMwRWEyeWZmQVB4UnVHZGlRNndsdFFRbnE0ak8rR1RUCkJYQ1BiOW9mc0tGOG5odjFYZGVZZmpBSWhQeVVmbkxnYU40RVBqMGUxZ2FBY1ZEVitVSzFZSVpYNUxuRWxRdDUKSCszMXJiVENldWVYZ3RqRGZkRlNJSUdtQmF3WWxmR3RWM2RRWGJuajZwZFQyejhUQkxrb1BkN01JVzdGQWdNQgpBQUdnQURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQW1UMDV4SHkxRDludmlDUGpHRmdycmVUQjVJTXZuOXdjCmNPRzBOaThNUlMyMUc0U2gzb2NyNUVveFRrbXRndDlialp5N3N5QUNNcXFHVHhueEh5VW4rSzEvZVZxdWhqeDkKdUlUU1ZzZFFRUE10OTJaYWR3OVZiTjdydGFMWDY1bU10T0dwVXNzeUhRQXpRSHdIbElKRWFjNjZxbE1oRlV4UAptZVc4ZFhqLysrUThrUnB6VjhsZ2MxSnRTYnhYbkpwR055eklObUozQU54N0RsQjVCQmtNRmJZRSswMlNQM1RVClgrNWdwY2NKZlBFZUxVMmM2dVVyM2ZLY2NybE5XenAveTE4Skwvc3Uvc3k4RG1zanB2ODdjRHNXMzZWcjNrTDIKaHBIYlJLRDZSdTJ2c0VvT2l2MW92dmZtTXhRMXNOMmd1aU05b0VYblRUUXJNUnU5Z2EyeHNRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  signerName: beta.eks.amazonaws.com/app-serving
  usages:
    - digital signature
    - key encipherment
    - server auth
