---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
 name: dev-kstadium-managed
 region: ap-northeast-2

iamIdentityMappings:
  - arn: arn:aws:iam::911781391110:role/EKS-Node-Role
    groups:
      - system:masters
      - system:bootstrappers
      - system:nodes
    username: system:node:{{EC2PrivateDNSName}}
    noDuplicateARNs: true # prevents shadowing of ARNs

  - arn: arn:aws:iam::911781391110:role/EKS-SA-Role
    groups:
      - system:masters
      - system:bootstrappers
      - system:node-proxier
      - system:nodes
    username: system:node:{{SessionName}}
    noDuplicateARNs: true # prevents shadowing of ARNs

  - arn: arn:aws:iam::911781391110:role/devops-role
    groups:
      - system:masters
      - system:bootstrappers
      - system:node-proxier
      - system:nodes
    username: system:node:{{SessionName}}
    noDuplicateARNs: true # prevents shadowing of ARNs

  - arn: arn:aws:iam::911781391110:role/AWSReservedSSO_crypted_devops_1c74128b3bb9822e
    groups:
      - system:masters
      - system:bootstrappers
      - system:node-proxier
      - system:nodes
    username: system:node:{{SessionName}}
    noDuplicateARNs: true # prevents shadowing of ARNs

iam:
  serviceRoleARN: arn:aws:iam::911781391110:role/EKS-Node-Role
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: eks-sa-role
      namespace: kube-system
    attachRoleARN: arn:aws:iam::911781391110:role/EKS-SA-Role

addons:
- name: vpc-cni
  version: latest
  serviceAccountRoleARN: arn:aws:iam::911781391110:role/EKS-Node-Role

vpc:
  id: vpc-09a6049b96e74bf58
  cidr: 10.10.0.0/16
  subnets:
    private:
      ap-northeast-2a:
         id: subnet-0bc60172da6da0e5e
      ap-northeast-2c:
         id: subnet-0d3309db6f0ad0260
    public:
      ap-northeast-2a:
         id: subnet-0515674ed4dc1772a
      ap-northeast-2c:
         id: subnet-0b89688a3a1ff4a93

managedNodeGroups:
  - name: nodegroup # 클러스터의 노드 그룹명
    instanceType: t3.medium # 클러스터 워커 노드의 인스턴스 타입
    desiredCapacity: 1 # 클러스터 워커 노드의 갯수
    volumeSize: 30  # 클러스터 워커 노드의 EBS 용량 (단위: GiB)
    privateNetworking: true
    ssh:
      enableSsm: true
    iam:
      instanceRoleARN: arn:aws:iam::911781391110:role/EKS-Node-Role

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
