apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  labels:
    intent: apps
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
    - key: karpenter.k8s.aws/instance-size
      operator: In
      values: ["medium"]
    - key: node.kubernetes.io/instance-type
      operator: In
      values: ["t3.medium"]
  limits:
    resources:
      cpu: 1000
      memory: 1000Gi
  ttlSecondsAfterEmpty: 30
  ttlSecondsUntilExpired: 2592000
  providerRef:
    name: default
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    kubernetes.io/cluster/dev-kstadium-gndchain: owned
  securityGroupSelector:
    aws:eks:cluster-name: dev-kstadium-gndchain
  instanceProfile: EKS-Node-Role
  tags:
    KarpenerProvisionerName: "default"
    NodeType: "karpenter-node"
