kind: ClusterConfig
apiVersion: eksctl.io/v1alpha5
metadata:
    name: dev-kstadium-managed
    region: ap-northeast-2

managedNodeGroups:
  - name: nodegroup-m5-xlarge # 클러스터의 노드 그룹명
    instanceType: m5.xlarge # 클러스터 워커 노드의 인스턴스 타입
    desiredCapacity: 1 # 클러스터 워커 노드의 갯수
    volumeSize: 30  # 클러스터 워커 노드의 EBS 용량 (단위: GiB)
    privateNetworking: true
    ssh:
      enableSsm: true
    iam:
      instanceRoleARN: arn:aws:iam::911781391110:role/EKS-Node-Role

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

