vpc:
  subnets:
    private:
      ap-northeast-2a:
         id: subnet-085c4de26b8ae878e
      ap-northeast-2c:
         id: subnet-08bd9d896cbd7c6ec
kind: ClusterConfig
apiVersion: eksctl.io/v1alpha5
metadata:
 name: stg-kstadium-service
 region: ap-northeast-2

managedNodeGroups:
  - name: test-nodegroup # 클러스터의 노드 그룹명
    instanceType: m5.large # 클러스터 워커 노드의 인스턴스 타입
    desiredCapacity: 1 # 클러스터 워커 노드의 갯수
    volumeSize: 30  # 클러스터 워커 노드의 EBS 용량 (단위: GiB)
    privateNetworking: true
    ssh:
      enableSsm: true
    iam:
      instanceRoleARN: arn:aws:iam::779626203419:role/EKS-Node-Role

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
