---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
 name: dev-reserved
 region: ap-northeast-2

iamIdentityMappings:
  - arn: arn:aws:iam::911781391110:role/eksFullAccessRole
    groups:
      - system:masters
      - system:bootstrappers
      - system:nodes
    username: system:node:{{EC2PrivateDNSName}}
    noDuplicateARNs: true # prevents shadowing of ARNs


  - arn: arn:aws:iam::911781391110:role/AWSReservedSSO_crypted_devops_1c74128b3bb9822e
    groups:
      - system:masters
      - system:bootstrappers
      - system:nodes
    username: system:node:{{EC2PrivateDNSName}}
    noDuplicateARNs: true # prevents shadowing of ARNs


  - arn: arn:aws:iam::911781391110:role/devops-role
    groups:
      - system:masters
      - system:bootstrappers
      - system:nodes
    username: system:node:{{EC2PrivateDNSName}}
    noDuplicateARNs: true # prevents shadowing of ARNs

iam:
  serviceRoleARN: arn:aws:iam::911781391110:role/eksFullAccessRole
  withOIDC: true

vpc:
  id: vpc-09a6049b96e74bf58
  cidr: 10.10.0.0/16
  subnets:
    private:
      ap-northeast-2a:
         id: subnet-0bc60172da6da0e5e
      ap-northeast-2c:
         id: subnet-0d3309db6f0ad0260
    public:
      ap-northeast-2a:
         id: subnet-0515674ed4dc1772a
      ap-northeast-2c:
         id: subnet-0b89688a3a1ff4a93

managedNodeGroups:
  - name: nodegroup # 클러스터의 노드 그룹명
    instanceType: m5.large # 클러스터 워커 노드의 인스턴스 타입
    desiredCapacity: 2 # 클러스터 워커 노드의 갯수
    volumeSize: 30  # 클러스터 워커 노드의 EBS 용량 (단위: GiB)
    privateNetworking: true
    ssh:
      enableSsm: true
    iam:
      #  withAddonPolicies:
      #    imageBuilder: true # Amazon ECR에 대한 권한 추가
      #    albIngress: true  # albIngress에 대한 권한 추가
      #    cloudWatch: true # cloudWatch에 대한 권한 추가
      #    autoScaler: true # auto scaling에 대한 권한 추가
      #    ebs: true # EBS CSI Driver에 대한 권한 추가
      instanceRoleARN: arn:aws:iam::911781391110:role/eksFullAccessRole

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

