---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
 name: dev-kstadium-gndchain
 region: ap-northeast-2

iamIdentityMappings:
  - arn: arn:aws:iam::911781391110:role/eksFullAccessRole
    groups:
      - system:masters
      - system:bootstrappers
      - system:nodes
    username: system:node:{{EC2PrivateDNSName}}
    noDuplicateARNs: true # prevents shadowing of ARNs


  - arn: arn:aws:iam::911781391110:role/AWSReservedSSO_crypted_devops_1c74128b3bb9822e
    groups:
      - system:masters
      - system:bootstrappers
      - system:node-proxier
      - system:nodes
    username: system:node:{{SessionName}}
    noDuplicateARNs: true # prevents shadowing of ARNs



iam:
  serviceRoleARN: arn:aws:iam::911781391110:role/eksFullAccessRole
  withOIDC: true

vpc:
  id: vpc-03cc4687074f4e7d7
  cidr: 10.11.0.0/16
  subnets:
    private:
      ap-northeast-2a:
         id: subnet-0f0036f4015024a5b
      ap-northeast-2c:
         id: subnet-078f130fd97bc382e
    public:
      ap-northeast-2a:
         id: subnet-0f3b347b9cfba958c
      ap-northeast-2c:
         id: subnet-053e60c49362851e0

managedNodeGroups:
  - name: nodegroup # 클러스터의 노드 그룹명
    instanceType: m5.large # 클러스터 워커 노드의 인스턴스 타입
    desiredCapacity: 2 # 클러스터 워커 노드의 갯수
    volumeSize: 30  # 클러스터 워커 노드의 EBS 용량 (단위: GiB)
    privateNetworking: true
    ssh:
      enableSsm: true
    iam:
      #  withAddonPolicies:
      #    imageBuilder: true # Amazon ECR에 대한 권한 추가
      #    albIngress: true  # albIngress에 대한 권한 추가
      #    cloudWatch: true # cloudWatch에 대한 권한 추가
      #    autoScaler: true # auto scaling에 대한 권한 추가
      #    ebs: true # EBS CSI Driver에 대한 권한 추가
      instanceRoleARN: arn:aws:iam::911781391110:role/eksFullAccessRole

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

