apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-frontend
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-fargate
  template:
    metadata:
      labels:
        app: frontend-fargate
    spec:
      containers:
        - name: demo-frontend
#          image: .dkr.ecr..amazonaws.com/demo-frontend:latest
          image: 911781391110.dkr.ecr.ap-northeast-2.amazonaws.com/demo-nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
