controller:
  replicas: 2
server:
  replicas: 2
  ingress: enable
   annotations:
      kubernetes.io/ingress.class: nginx
  service:
    annotations: {}
    labels: {}
    #type: ingress
    #type: NodePort
    #type: ClusterIP
    nodePortHttp: 30080
    nodePortHttps: 30443
    servicePortHttp: 80
    servicePortHttps: 443
    servicePortHttpName: http
    servicePortHttpsName: https
    namedTargetPort: true
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    externalIPs: []
    externalTrafficPolicy: ""
    sessionAffinity: ""
