apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-csr-create-binding
subjects:
- kind: User
  name: system:node:<node-name>
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: node-csr-create
  apiGroup: rbac.authorization.k8s.io
